### PR TITLE
[Pull Request] Rewrite installer with rust and egui instead of dotnet framework.

### PR DESCRIPTION
**Pull request by Dynesshely**
## What does this PR do?

I rewrited old installer in rust with egui, witch is cross-platforms and fast.
We can use this solution to create simple and fast installer.

### Progress

I had finished ui design and installation steps design.
Next, I'm going to realize actually installation codes.

## Related issues

- Crequency/KitX#264 .

### CODE REVIEW

**Comment by Dynesshely** [comment]
I'm going to display some screenshots for new installer:

<details>
<summary>Screenshots</summary>
<p>

Select language:

image

Hello:

image

License:

image

Installation config:

image

Installing:

image

Finish:

image

</p>
</details>

**Comment by Dynesshely** [comment]
In below commits:

- [💾 Feat: Adapt to linux.](https://github.com/Crequency/KitX-Installer/pull/1/commits/d828548cb037995befb12ee9fe7fa8a98af3f158)
- [🔧 Fix(Linux): Some issues on linux platform.](https://github.com/Crequency/KitX-Installer/pull/1/commits/51b3b0e3b50fd38995c2a28a715d7ceb318888fb)

I added support for linux platform, now we can run both gui and shell mode on linux to install `KitX Dashboard`.

**Comment by Dynesshely** [comment]
A patcher that patched the original installer file has been done.

**Comment by Dynesshely** [comment]
A lots of enhancements !
Patching installer became easier .
Now it can download installation file .

**Comment by Dynesshely** [comment]
Now installer can extract installation file (7z) to installation path.
Embedded a new font to replace default font.

**Comment by Dynesshely** [comment]
All is done !

// TODO: Open `KitX Dashboard` after installer window closed if user checked.

**Review by langyo — COMMENTED** [review]
These part looks not done yet..

**Review by langyo — COMMENTED** [review]
The config's default value looks not compatable to anyone, which there's a fixed installing path with private user name.

**Review by StardustSeemsInk — APPROVED** [review]
What a NICE work!

**Review by LYF511 — APPROVED** [review]
Nice simple installer

**Comment by Dynesshely** [comment]
So, I'm going to merge this.

**Pull request merged**
